version: '3.6'

services:

  api:
    depends_on:
      - postgresql
    image: orgo/api
    ports:
      - 3000:3000
    volumes:
      - ./api/package.json:/home/app/package.json
      - ./api/src:/home/app/src
      - ./api/tests:/home/app/tests

  webspicy:
    depends_on:
      - api
    environment:
      LOG_LEVEL: DEBUG
    image: orgo/webspicy
    volumes:
      - ./webspicy/config.rb:/webspicy/config.rb
      - ./webspicy/schema.fio:/webspicy/schema.fio
      - ./webspicy/api:/webspicy/api

  dbagent:
    depends_on:
      - postgresql
    image: orgo/dbagent
    volumes:
      - ./dbagent/data:/home/app/data
      - ./dbagent/migrations:/home/app/migrations
      - ./dbagent/schema:/home/app/schema
    environment:
      DBAGENT_HOST: postgresql
      DBAGENT_USER: orgo
      DBAGENT_PASSWORD: orgo
      DBAGENT_DB: orgo

  postgresql:
    image: postgres:12.4
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: orgo
      POSTGRES_USER: orgo
      POSTGRES_DB: orgo
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  # webspicy:
  #     image: orgo/webspicy
  #     env_file:
  #       ./webspicy/env/devel.env
  #     volumes:
  #     - ./webspicy/Rakefile:/home/app/Rakefile
  #     - ./webspicy/formaldoc:/home/app/formaldoc
  #     - ./webspicy/domain:/home/app/domain

  frontend:
    image: orgo/frontend-builder
    command: npm run serve
    volumes:
      - ./frontend/public:/home/app/public
      - ./frontend/src:/home/app/src
      - ./frontend/babel.config.js:/home/app/babel.config.js
      - ./frontend/package.json:/home/app/package.json

  gateway:
    image: orgo/gateway
    env_file:
      ./gateway/env/devel.env
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
